name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Check api
        run: ./gradlew apiCheck

  build-android:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Test android targets
      run: ./gradlew testDebugUnitTest testReleaseUnitTest

  build-apple:
    runs-on: macos-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test apple targets
        run: ./gradlew iosX64Test iosSimulatorArm64Test macosX64Test macosArm64Test tvosX64Test tvosSimulatorArm64Test watchosX64Test watchosSimulatorArm64Test

  build-windows:
    runs-on: windows-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test windows targets
        continue-on-error: true # https://github.com/square/okio/issues/951
        run: ./gradlew windowsTest

  build-linux:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test linux targets
        run: ./gradlew linuxTest

  build-js:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test js targets
        run: ./gradlew jsTest

  build-desktop:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test desktop targets
        run: ./gradlew desktopTest

  release:
    runs-on: ubuntu-latest
    needs:
      - build-android
      - build-apple
      - build-windows
      - build-linux
      - build-js
      - build-desktop
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Write secrets to local.properties
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo sonatypeUsername="${SONATYPE_USERNAME}" >> "local.properties"
        echo sonatypePassword="${SONATYPE_PASSWORD}" >> "local.properties"
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Publish to sonatype
      if: ${{ github.event_name != 'pull_request' }}
      run: ./gradlew publishAllPublicationsToMavenRepository
